name: workflow-for-Go-app
on:
   push:
      branches:
        - main
   workflow_dispatch:
jobs:
  job1-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
         go-version:  '1.25.1'

      - name: Cache Go dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path:  |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: go mod tidy
        working-directory: fancy-adventure
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0
      - name: Add golangci-lint to PATH
        run: echo "$GOPATH/bin" >> $GITHUB_PATH
      - name: Running tests
        run: go test ./... -v
        working-directory: fancy-adventure/

      - name: Running linter
        run: golangci-lint run
        working-directory: fancy-adventure

# commenst

       
   